### ISSUE TITLE
Can only create one logical switch

### ISSUE THREAD

**Issue by GSAAS** [vmware/nsxansible#1]
Tried creating more than one logical switch and code was failing stating that the  LS Switch ID was 0.  Turned out there was a missing return in get_lswitch_id () that is part of nsx_logical_switch in the library...  Change was discovered by @jkarnes32

The last return is what was missing: 

def get_lswitch_id(session, lswitchname, scope):
    tz_lswitches=session.read('logicalSwitches', uri_parameters={'scopeId': scope})['body']
    try:
        first_page=tz_lswitches['virtualWires']['dataPage']['virtualWire']
    except KeyError:
        return []
    if isinstance(first_page, dict) and lswitchname in first_page['name']:
        return [first_page['objectId']]
    elif isinstance(first_page, list):
        return [lswitch['objectId'] for lswitch in first_page if lswitchname in lswitch['name']]
*\*    return []**

**Comment by yfauser** [comment]
Closed with Commit: Merge pull request #2 from VMwareGSAAS/master
