### ISSUE TITLE
Add ESG and DLR deployment functionality

### ISSUE THREAD

**Issue by trickydee** [vmware/nsxansible#10]
I have a requirement to deploy ESG and DLR routing functions. 
My requirements are that a ESG functionality can be deployed, with an without HA.
Additionaly I need to be able to provision static routing and dynamic OSPF routing.

**Comment by yfauser** [comment]
- [x] ESG Create and deletion
- [x] DLR Create and deletion
- [x] ESG deploy with HA / Non-HA
- [x] DLR deploy with HA / Non-HA
- [x] ESG & DLR default firewall state
- [x] ESG & DLR static routing
- [x] ESG & DLR default gateway
- [x] ESG OSPF (with idempotent routing config)
- [x] DLR OSPF (with idempotent routing config)
