### ISSUE TITLE
Enhance Error handling when Transport Zone is wrong in logical switch module

### ISSUE THREAD

**Issue by yfauser** [vmware/nsxansible#28]
Right now when the TZ is not found by the  logical switch module, you only get:
The error was: TypeError: object of type 'NoneType' has no len()

We need to catch this error and report a proper module failure

**Comment by pandom** [comment]
I am glad I read the issue log.

This is the -vvv output:

`task path: /Users/aburke/Documents/GitHub/nsxansible/test_logicalswitch.yml:8
Using module file /Users/aburke/Documents/GitHub/nsxansible/library/nsx_logical_switch.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: aburke
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1484787651.63-42380894537558 `" && echo ansible-tmp-1484787651.63-42380894537558="` echo $HOME/.ansible/tmp/ansible-tmp-1484787651.63-42380894537558 `" ) && sleep 0'
<localhost> PUT /var/folders/16/wyns845574z40lqr04g5b_p80000gn/T/tmpnBIYHn TO /Users/aburke/.ansible/tmp/ansible-tmp-1484787651.63-42380894537558/nsx_logical_switch.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/aburke/.ansible/tmp/ansible-tmp-1484787651.63-42380894537558/ /Users/aburke/.ansible/tmp/ansible-tmp-1484787651.63-42380894537558/nsx_logical_switch.py && sleep 0'
<localhost> EXEC /bin/sh -c '/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python /Users/aburke/.ansible/tmp/ansible-tmp-1484787651.63-42380894537558/nsx_logical_switch.py; rm -rf "/Users/aburke/.ansible/tmp/ansible-tmp-1484787651.63-42380894537558/" > /dev/null 2>&1 && sleep 0'`

This is the exception code:

`An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/16/wyns845574z40lqr04g5b_p80000gn/T/ansible_pOMPzF/ansible_module_nsx_logical_switch.py", line 117, in <module>
    main()
  File "/var/folders/16/wyns845574z40lqr04g5b_p80000gn/T/ansible_pOMPzF/ansible_module_nsx_logical_switch.py", line 82, in main
    lswitch_id=get_lswitch_id(client_session, module.params['name'], vdn_scope)
  File "/var/folders/16/wyns845574z40lqr04g5b_p80000gn/T/ansible_pOMPzF/ansible_module_nsx_logical_switch.py", line 32, in get_lswitch_id
    lswitches_api = session.read_all_pages('logicalSwitches', uri_parameters={'scopeId': scope})
  File "/Library/Python/2.7/site-packages/nsxramlclient/client.py", line 234, in read_all_pages
    additional_headers)['body']
  File "/Library/Python/2.7/site-packages/nsxramlclient/client.py", line 144, in _request
    resource_url = self._nsxraml.contruct_resource_url(searched_resource, uri_parameters)
  File "/Library/Python/2.7/site-packages/nsxramlclient/client.py", line 341, in contruct_resource_url
    resource_url = re.sub('\{' + uri_parameter + '\}', uri_parameters[uri_parameter], resource_url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 286, in _subx
    template = _compile_repl(template, pattern)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 271, in _compile_repl
    p = sre_parse.parse_template(repl, pattern)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.py", line 737, in parse_template
    s = Tokenizer(source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.py", line 192, in __init__
    self.__next()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.py", line 194, in __next
    if self.index >= len(self.string):
TypeError: object of type 'NoneType' has no len()

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "nsx_logical_switch"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/16/wyns845574z40lqr04g5b_p80000gn/T/ansible_pOMPzF/ansible_module_nsx_logical_switch.py\", line 117, in <module>\n    main()\n  File \"/var/folders/16/wyns845574z40lqr04g5b_p80000gn/T/ansible_pOMPzF/ansible_module_nsx_logical_switch.py\", line 82, in main\n    lswitch_id=get_lswitch_id(client_session, module.params['name'], vdn_scope)\n  File \"/var/folders/16/wyns845574z40lqr04g5b_p80000gn/T/ansible_pOMPzF/ansible_module_nsx_logical_switch.py\", line 32, in get_lswitch_id\n    lswitches_api = session.read_all_pages('logicalSwitches', uri_parameters={'scopeId': scope})\n  File \"/Library/Python/2.7/site-packages/nsxramlclient/client.py\", line 234, in read_all_pages\n    additional_headers)['body']\n  File \"/Library/Python/2.7/site-packages/nsxramlclient/client.py\", line 144, in _request\n    resource_url = self._nsxraml.contruct_resource_url(searched_resource, uri_parameters)\n  File \"/Library/Python/2.7/site-packages/nsxramlclient/client.py\", line 341, in contruct_resource_url\n    resource_url = re.sub('\\{' + uri_parameter + '\\}', uri_parameters[uri_parameter], resource_url)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py\", line 155, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py\", line 286, in _subx\n    template = _compile_repl(template, pattern)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py\", line 271, in _compile_repl\n    p = sre_parse.parse_template(repl, pattern)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.py\", line 737, in parse_template\n    s = Tokenizer(source)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.py\", line 192, in __init__\n    self.__next()\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.py\", line 194, in __next\n    if self.index >= len(self.string):\nTypeError: object of type 'NoneType' has no len()\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}`
