### ISSUE TITLE
Enhance ESG code to enable ECMP mode

### ISSUE THREAD

**Issue by COvirtNetwork** [vmware/nsxansible#32]
I would like to request a feature to enable ECMP mode on an Edge - not sure if the preferred method would be through the nsx_edge_router module, or through the respective routing protocol modules (i.e. nsx_ospf)

**Comment by yfauser** [comment]
@jtompkins81 Thanks for the request! I will have more time to work on the modules in the next weeks. I'll add ECMP support, it makes a lot of sense.
