### ISSUE TITLE
Need module to add license for NSX deployment

### ISSUE THREAD

**Issue by yfauser** [vmware/nsxansible#38]
The new licensing is breaking the deployment playbook.
This is a requirement since the introduction of different license types for NSX.
Two options:
1.       Press any key to continue with a message “Please add license in vCenter”
2.       To see how pyvmomi can add license and to add the license key in the answerfile

The second Option is preferred

**Comment by yasensim** [comment]
I have added this in as a library and one can specify the license key in the answerfile. I will push it today.

**Comment by jdatx** [comment]
@yasensim very interested to see this!

**Comment by yasensim** [comment]
@jdatx it is already in devel branch

**Comment by yasensim** [comment]
added to devel branch
