### ISSUE TITLE
nsx_transportzone fails if transport zone exists

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [vmware/nsxansible#49]
When I create a transport zone with

    - name: Transport Zone
      nsx_transportzone:
        name: test-transport-zone
        state: present

        cluster_moid_list:
          - domain-c9 # sy2-cl-comp-easq-001
          
        nsxmanager_spec:
          raml_file: '/home/foo/nsxraml/nsxvapi.raml'
          host: "{{ nsx_address }}"
          user: "{{ nsx_user }}"
          password: "{{ nsx_password }}"

it works the first time. But when I run this again I get the following error:

    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'description'
    fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_HW5z4B/ansible_module_nsx_transportzone.py\", line 183, in <module>\n    main()\n  File \"/tmp/ansible_HW5z4B/ansible_module_nsx_transportzone.py\", line 174, in main\n    scope_state[module.params['state']][check_scope_states(s, module.params['name'])](s, module)\n  File \"/tmp/ansible_HW5z4B/ansible_module_nsx_transportzone.py\", line 119, in state_check_scope_update\n    vdn_props = get_vdnscope_properties(session, vdn_scope_id)\n  File \"/tmp/ansible_HW5z4B/ansible_module_nsx_transportzone.py\", line 41, in get_vdnscope_properties\n    vdnscope_properties['description'] = vdn_scope_content['vdnScope']['description']\nKeyError: 'description'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

**Comment by dennis-benzinger-hybris** [comment]
I guess the problem is that the `description` field is optional when creating the transport zone. But when the module checks the current status of the transport zone it expects it to be there.

**Comment by yfauser** [comment]
@dennis-benzinger-hybris Thanks for reporting this, and sorry for the delay. I will look at it in the next days

**Comment by yfauser** [comment]
@dennis-benzinger-hybris I committed a change into the 'devel' branch. Can you please verify it before I merge it into master? Thanks!
