### ISSUE TITLE
does not allow creating EDGE with Standard Port group 

### ISSUE THREAD

**Issue by srinarayanant** [vmware/nsxansible#53]
changing the VIM type search to 'portgroup_name': [vim.host.PortGroup]} in below 

```
VIM_TYPES = {'datacenter': [vim.Datacenter],
             'dvs_name': [vim.dvs.VmwareDistributedVirtualSwitch],
             'datastore_name': [vim.Datastore],
             'resourcepool_name': [vim.ResourcePool],
'portgroup_name': [vim.dvs.DistributedVirtualPortgroup]}
```
[](
https://github.com/vmware/nsxansible/blob/master/library/vcenter_gather_moids.py
)

gives error 

> The full traceback is:
> Traceback (most recent call last):
>   File "/tmp/ansible_1PP18T/ansible_module_vcenter_gather_moids.py", line 94, in <module>
>     main()
>   File "/tmp/ansible_1PP18T/ansible_module_vcenter_gather_moids.py", line 82, in main
>     object_mo = get_mo(content, module.params[searched_parameter], VIM_TYPES[searched_parameter])
>   File "/tmp/ansible_1PP18T/ansible_module_vcenter_gather_moids.py", line 37, in get_mo
>     mo = get_all_objs(content, vim_type_list)
>   File "/tmp/ansible_1PP18T/ansible_modlib.zip/ansible/module_utils/vmware.py", line 348, in get_all_objs
>   File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
>     self.f(*(self.args + (obj,) + args), **kwargs)
>   File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
>     return self._stub.InvokeMethod(self, info, args)
>   File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
>     raise obj # pylint: disable-msg=E0702
> pyVmomi.VmomiSupport.InvalidArgument: (vmodl.fault.InvalidArgument) {
>    dynamicType = <unset>,
>    dynamicProperty = (vmodl.DynamicProperty) [],
>    msg = 'A specified parameter was not correct: type',
>    faultCause = <unset>,
>    faultMessage = (vmodl.LocalizableMessage) [],
>    invalidProperty = u'type'
> }
> 
>

**Comment by srinarayanant** [comment]
Files in question : 
https://github.com/vmware/nsxansible/blob/master/test_esg.yml
https://github.com/vmware/nsxansible/blob/master/library/vcenter_gather_moids.py

**Comment by yfauser** [comment]
@srinarayanant @yasensim 
The vcenter_gather_moids module already had the capability to find VSS portgroups as well as
VDS portgroups, but the code was not merged into master yet. This commit is cleaning up the code just a bit, and enhances error reporting when the searched object is not found

**Comment by srinarayanant** [comment]
Great !! its good now  , thank u
