### ISSUE TITLE
nsx_edge_nat module always return ok status and creates duplicates

### ISSUE THREAD

**Issue by a-nanasov** [vmware/nsxansible#70]
nsx_edge_nat module always return ok status in the ansible-playbook output and creates NAT rules duplicates with each playbook run

**Comment by virtualelephant** [comment]
@Kenuat Thank you for the report.

The API has two methods for creating and adding NAT rules. Currently the Ansible module only has the first method implemented. I am working on implementing the second method and will resolve the issue shortly.

> PUT /api/4.0/edges/{edgeId}/nat/config
> URI Parameters:
> Description:
> Configure SNAT and DNAT rules for an Edge.
> If you use this method to add new NAT rules, you must include all existing rules in the request body. Any rules that are omitted will be deleted.

> POST /api/4.0/edges/{edgeId}/nat/config/rules
> URI Parameters:
> Query Parameters:
> Description:
> Add a NAT rule above a specific rule in the NAT rules table (using aboveRuleId query parameter) or append NAT
> rules to the bottom.

**Comment by virtualelephant** [comment]
Update modules. Choose from create or append. Note the create method will remove all existing NAT rules on the Edge and replace it with the new set. Append will add a new rule before or after any existing rule.
